services:
  - type: web
    name: citation-finder
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SYSTEM_PROMPT
        sync: false
      - key: USER_PROMPT
        sync: false
